import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: '개발사항 입력',
  description: 'Generated by HoiYoeb',
};

export default function Layout({ children }: { children: React.ReactNode }) {
    return (
        <form>
            <h2>Create!!</h2>
            {children}
        </form>
    )
}