import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: '안녕하세요 정회엽입니다.',
  description: 'Generated by HoiYoeb',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body>
        <h1>Frontend Developer</h1>
        <h2>정회엽</h2>
        <ul>
          <li><a href='/career'>1.Career</a></li>
        </ul>
        {children}
        <ul>
          <li><a href='/create'>Create</a></li>
          <li><a href='/update/1'>Update</a></li>
        </ul>
      </body>
    </html>
  );
}
